# Dockerfile.backend
FROM python:3.11-slim

WORKDIR /app

# Install required system packages
RUN apt-get update && apt-get install -y gcc libmysqlclient-dev default-libmysqlclient-dev

# Install Python dependencies
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend code
COPY backend/ .

CMD ["python", "scrapper.py"]

