# Dockerfile.frontend
FROM node:18 AS build

WORKDIR /app
COPY frontendbuild/ ./

RUN npm install && npm run build

# Serve static build with nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
