# Dockerfile.backend
FROM python:3.10-slim

WORKDIR /app

COPY backend/scrapper.py backend/requirements.txt ./

RUN apt-get update && apt-get install -y gcc libmariadb-dev vim && apt-get clean \
    && pip install --no-cache-dir -r requirements.txt

ENV DB_HOST=cicdrdsdb.cjgiuuuoiuzk.ap-south-1.rds.amazonaws.com \
    DB_USER=admin \
    DB_PASSWORD=password123 \
    DB_NAME=dbtenders \
    DB_PORT=3306

CMD ["python3", "scrapper.py"]
